AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Stage:
    Type: String

Resources:
  cldFormationTempBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
          Fn::Join:
                - ""
                - - "cloud-formation-temp-bucket"
                  - !Ref Stage
                  - "-"
                  - !Ref AWS::AccountId
                  - "-"
                  - !Ref AWS::Region
      AccessControl: Private

  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "SampleTopic"

  MySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: sreeananthakannan@gmail.com
      Protocol: email
      TopicArn: !Ref 'MySNSTopic'

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName:
        Fn::Join:
                - ""
                - - "user-pool"
                  - !Ref Stage
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName:
        Fn::Join:
                - ""
                - - "user-pool-client"
                  - !Ref Stage
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false


Outputs:
  cldFormationTempBucketARN:
    Value: !GetAtt
            - cldFormationTempBucket
            - Arn
    Description: The temp bucket created using cloudformation script
    Export:
      Name: cldFormationTempBucketARN

  MySubscriptionARN:
    Value: !Ref MySubscription
    Description: The subscription created
    Export:
      Name: MySubscriptionARN

  MySNSTopicARN:
    Value: !Ref MySNSTopic
    Description: The SNS Topic created
    Export:
      Name: MySNSTopicARN

  CognitoUserPoolARN:
    Value: !GetAtt
            - CognitoUserPool
            - Arn
    Description: The CognitoUserPool created
    Export:
      Name: CognitoUserPoolARN
    
  CognitoUserPoolClientARN:
    Value: !GetAtt
            - CognitoUserPoolClient
            - Arn
    Description: The Cognito user pool client created
    Export:
      Name: CognitoUserPoolClientARN