AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Stage:
    Type: String

Resources:
  cldFormationTempBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
          Fn::Join:
                - ""
                - - "cloud-formation-temp-bucket"
                  - !Ref Stage
                  - "-"
                  - !Ref AWS::AccountId
                  - "-"
                  - !Ref AWS::Region
      AccessControl: Private

  Bucket:
        Type: AWS::S3::Bucket
        Properties:
            AccessControl: Private
            BucketName: private-bucket
            Tags:
                - Key: description
                  Value: "Private files"
  # CloudFrontOriginIdentity:
  #   Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
  #   Properties:
  #     CloudFrontOriginAccessIdentityConfig:
  #       Comment: 'origin identity'
  
  # BucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket: private-bucket
  #     PolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginIdentity}'
  #           Action: 's3:GetObject'
  #           Resource: arn:aws:s3:::private-bucket/*
  
  # publicDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: private-bucket.s3.us-east-2.amazonaws.com
            Id: S3-private-bucket
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginIdentity}'
        Enabled: 'true'
        Comment: Some comment
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: S3-private-bucket
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'

  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "SampleTopic"

  MySNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref MySNSTopic
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: sns:Publish
            Resource: !Ref MySNSTopic

  MySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: sreeananthakannan@gmail.com
      Protocol: email
      TopicArn: !Ref 'MySNSTopic'

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName:
        Fn::Join:
                - ""
                - - "user-pool"
                  - !Ref Stage
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName:
        Fn::Join:
                - ""
                - - "user-pool-client"
                  - !Ref Stage
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false


Outputs:
  cldFormationTempBucketARN:
    Value: !GetAtt
            - cldFormationTempBucket
            - Arn
    Description: The temp bucket created using cloudformation script
    Export:
      Name: cldFormationTempBucketARN

  MySubscriptionARN:
    Value: !Ref MySubscription
    Description: The subscription created
    Export:
      Name: MySubscriptionARN

  MySNSTopicARN:
    Value: !Ref MySNSTopic
    Description: The SNS Topic created
    Export:
      Name: MySNSTopicARN

  CognitoUserPoolARN:
    Value: !GetAtt
            - CognitoUserPool
            - Arn
    Description: The CognitoUserPool created
    Export:
      Name: CognitoUserPoolARN
  CognitoUserPoolClientARN:
    Value: !Ref CognitoUserPoolClient
    Description: The Cognito user pool client created
    Export:
      Name: CognitoUserPoolClientARN