AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Stage:
    Type: String

Resources:
  cldFormationTempBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
          Fn::Join:
                - ""
                - - "cloud-formation-temp-bucket"
                  - !Ref Stage
                  - "-"
                  - !Ref AWS::AccountId
                  - "-"
                  - !Ref AWS::Region
      AccessControl: Private

  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint:
            Fn::GetAtt:
              - "MySubscription"
              - "Arn"
          Protocol: "email"
        # - Endpoint:
        #     Fn::GetAtt:
        #       - "MyQueue2"
        #       - "Arn"
        #   Protocol: "sqs"
      TopicName: "SampleTopic"

  MySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: sreeananthakannan@gmail.com
      Protocol: email
      TopicArn: !Ref 'MySNSTopic'


Outputs:
  cldFormationTempBucketARN:
    Value: !GetAtt
            - cldFormationTempBucket
            - Arn
    Description: The temp bucket created using cloudformation script
    Export:
      Name: cldFormationTempBucketARN