AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Stage:
    Type: String

Resources:
  cldFormationTempBucket:
    Type: 'AWS::S3::Bucket'
    BucketName:
          Fn::Join:
                - ""
                - - "cloud-formation-temp-bucket"
                  - !Ref Stage
                  - "-"
                  - !Ref AWS::AccountId
                  - "-"
                  - !Ref AWS::Region
    Properties:
      AccessControl: Private


Outputs:
  cldFormationTempBucketARN:
    Value: !GetAtt
            - cldFormationTempBucket
            - Arn
    Description: The temp bucket created using cloudformation script
    Export:
      Name: cldFormationTempBucketARN